# Trigger definition
on:
  push:
    branches: ["master"]

# Set permissions (corrected)
permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle 
        uses: gradle/setup-gradle@v3
